kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ad-service-api-allow
spec:
  podSelector:
    matchLabels:
      app: adservice
  ingress:
  - from:
    podSelector:
      matchLabels:
        app: frontend
    namespaceSelector:
      matchLabels:
        purpose: g2g

---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: app
  name: deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
