---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reduce-ads
spec:
  host: "*"
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reduce-ads
spec:
  hosts:
  - "*"
  gateways:
  - ext-host-gwy
  http:
  - route:
    - destination:
        host: frontend
        subset: v1
      weight: 90
    - destination:
        host: frontendv2
        subset: v2
      weight: 10
